// src/components/Navbar.jsx
import { useState, useEffect } from 'react'
import { useTheme } from '../hooks/useTheme'

const NAV_LINKS = [
  { label: 'About', href: '#about' },
  { label: 'Skills', href: '#skills' },
  { label: 'Experience', href: '#experience' },
  { label: 'Projects', href: '#projects' },
  { label: 'Contact', href: '#contact' },
]

function SunIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41" />
    </svg>
  )
}

function MoonIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  )
}

function MenuIcon() {
  return (
    <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" viewBox="0 0 24 24">
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}

function CloseIcon() {
  return (
    <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" viewBox="0 0 24 24">
      <path d="M18 6 6 18M6 6l12 12" />
    </svg>
  )
}

export default function Navbar({ onResumeOpen }) {
  const { isDark, toggle } = useTheme()
  const [scrolled, setScrolled] = useState(false)
  const [open, setOpen] = useState(false)

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20)
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  const scrollTo = (href) => {
    setOpen(false)
    document.querySelector(href)?.scrollIntoView({ behavior: 'smooth' })
  }

  return (
    <header
      className={`fixed top-0 inset-x-0 z-50 bg-white dark:bg-[#0f0f0f] transition-colors duration-300 ${
        scrolled ? 'border-b border-gray-100 dark:border-white/5 shadow-sm' : ''
      }`}
    >
      <div className="max-w-5xl mx-auto px-6 h-14 flex items-center justify-between">
        {/* Logo */}
        <button
          onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
          className="text-sm font-semibold text-gray-900 dark:text-gray-100 transition-colors duration-150 hover:text-gray-600 dark:hover:text-gray-400"
        >
          Adrian Lylle Bona
        </button>

        {/* Desktop nav */}
        <nav className="hidden lg:flex items-center gap-7">
          {NAV_LINKS.map(({ label, href }) => (
            <a
              key={href}
              href={href}
              onClick={(e) => { e.preventDefault(); scrollTo(href) }}
              className="nav-link"
            >
              {label}
            </a>
          ))}
        </nav>

        {/* Theme toggle + Resume + hamburger */}
        <div className="flex items-center gap-2">
          {/* Theme toggle — Sun = light mode active, Moon = dark mode active */}
          <button
            onClick={toggle}
            aria-label={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
            className="p-2 rounded-md text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 hover:bg-gray-100 dark:hover:bg-white/8 transition-colors duration-150"
          >
            {isDark ? <MoonIcon /> : <SunIcon />}
          </button>

          <button
            onClick={onResumeOpen}
            className="hidden lg:inline-flex btn-outline py-1.5 px-4 text-xs"
          >
            Resume
          </button>

          <button
            onClick={() => setOpen((v) => !v)}
            className="lg:hidden p-1.5 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors duration-150"
            aria-label={open ? 'Close menu' : 'Open menu'}
          >
            {open ? <CloseIcon /> : <MenuIcon />}
          </button>
        </div>
      </div>

      {/* Mobile menu */}
      {open && (
        <div className="lg:hidden border-t border-gray-100 dark:border-white/5 bg-white dark:bg-[#0f0f0f] transition-colors duration-300 px-6 py-5 flex flex-col gap-5">
          {NAV_LINKS.map(({ label, href }) => (
            <a
              key={href}
              href={href}
              onClick={(e) => { e.preventDefault(); scrollTo(href) }}
              className="text-sm font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors duration-150"
            >
              {label}
            </a>
          ))}
          <div className="pt-2 border-t border-gray-100 dark:border-white/5">
            <button
              onClick={() => { setOpen(false); onResumeOpen() }}
              className="btn-primary"
            >
              Resume
            </button>
          </div>
        </div>
      )}
    </header>
  )
}

// src/components/Navbar.vue
<script setup>
import { ref } from 'vue'
import { useTheme } from '../composables/useTheme'

const links = [
  { href: '#home', label: 'Home' },
  { href: '#projects', label: 'Projects' },
  { href: '#about', label: 'About' },
  { href: '#contact', label: 'Contact' },
]

const isOpen = ref(false)
const { dark, toggleTheme } = useTheme()

function toggleMenu() { isOpen.value = !isOpen.value }
function closeMenu() { isOpen.value = false }
</script>

<template>
  <header class="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur dark:border-gray-700 dark:bg-gray-900/95">
    <nav class="mx-auto flex w-full max-w-6xl items-center justify-between px-4 py-3 sm:px-6 sm:py-4 lg:px-10">
      <a href="#home" class="text-sm font-semibold tracking-tight text-slate-900 transition hover:opacity-70 dark:text-white sm:text-base">Adrian Bona</a>
      <div class="flex items-center gap-3">
        <button @click="toggleTheme" class="inline-flex h-10 w-10 items-center justify-center rounded-full transition hover:bg-slate-100 dark:hover:bg-gray-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-400" aria-label="Toggle theme">
          <span v-if="dark">☀️</span>
          <span v-else>🌙</span>
        </button>
        <button @click="toggleMenu" type="button" class="inline-flex h-10 items-center justify-center rounded-xl border border-slate-200 px-4 text-sm text-slate-700 transition hover:bg-slate-100 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-gray-800 lg:hidden">
          Menu
        </button>
        <ul class="hidden items-center gap-1 lg:flex">
          <li v-for="link in links" :key="link.href">
            <a :href="link.href" class="block rounded-xl px-4 py-2 text-sm font-medium text-slate-600 transition hover:bg-slate-100 hover:text-slate-900 dark:text-gray-300 dark:hover:bg-gray-800 dark:hover:text-white">
              {{ link.label }}
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <div :class="['border-t border-slate-200 bg-white px-4 py-3 dark:border-gray-700 dark:bg-gray-900 lg:hidden', isOpen ? 'block' : 'hidden']">
      <ul class="space-y-1">
        <li v-for="link in links" :key="'m' + link.href">
          <a :href="link.href" @click="closeMenu" class="block rounded-xl px-4 py-3 text-sm text-slate-700 transition hover:bg-slate-100 hover:text-slate-900 dark:text-gray-300 dark:hover:bg-gray-800 dark:hover:text-white">
            {{ link.label }}
          </a>
        </li>
      </ul>
    </div>
  </header>
</template>
